### ISSUE TITLE
Cisco SG220 series not working with ciscosmb.rb

### ISSUE THREAD

**Issue by packetkicker** [ytti/oxidized#1148] opened 2018-01-15 15:01 UTC
Hi,

I have been using Oxidized for the last few months to backup configurations from various pfSense, Cisco, Cisco SMB and Ubiquiti devices which has been working really well so far.  Had an install last week with 5 x Cisco SG220-26P switches.  Have set these up with SSH access but there seems to be an issue that Oxidized will not get past the login.

I can connect to the device ok from the command line on the oxidized server:

```
[oxidized@oxidized ~]$ ssh cisco@1.2.3.4 -p 8082












        Welcome to Layer 2 Managed Switch












  Press <Enter> to continue...
Username: cisco
Password: ********
DATA-SW-01#
```

I do not have to press enter for the Username: prompt to show.

I see the same in the /home/oxidized/.config/oxidized/logs/1.2.3.4-ssh log.

Any ideas what I should try to troubleshoot this further?

On Cisco SG300 series switches I normally have to change the SSH settings with `ip ssh password-auth` but this is not supported on the SG220 series.

![screen shot 2018-01-15 at 15 08 02](https://user-images.githubusercontent.com/28621135/34948860-415b39cc-fa06-11e7-9b5e-52ff58e2c0f0.png)

Where on the SG300 and above there are more options:

![screen shot 2018-01-15 at 15 12 04](https://user-images.githubusercontent.com/28621135/34948943-82d1f8b4-fa06-11e7-9c77-299fbd44000c.png)

Oxidized is v0.21.0

Thanks,
PK

**Comment by mattie47** [comment] 2018-01-16 03:57
@packetkicker 

>Have set these up with SSH access but there seems to be an issue that Oxidized will not get past the login.

Please paste the output to /home/oxidized/.config/oxidized/logs/1.2.3.4-ssh to here or on pastebin so we can see at exactly what point it's failing. 

If you find it doing something like:

```
Trying 10.37.105.10...
Connected to 10.37.105.10.
c2-access1 login: cisco
Password:
Trying 10.37.105.10...
Connected to 10.37.105.10.
c2-access1 login: cisco
Password:
Trying 10.37.105.10...
Connected to 10.37.105.10.
c2-access1 login: cisco
Password:
```

Then there's probably something wrong with the oxidized config file for the vendor model. I guess another thing to confirm is ensure your oxidized model mapping is mapping your device to the correct model. 

You can check all the device models by (probably) looking in 
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/model/

If your install location differs, you can use:
```
librenms@librenmsdev:/home/oxidized/.config/oxidized/logs$ gem which oxidized
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized.rb
```

Thanks,

Matt

**Comment by packetkicker** [comment] 2018-01-16 13:40
Hi Matt,

My current confirm file is [https://pastebin.com/vATpucch](url) and the SSH log for that device is [https://pastebin.com/UwKbwZXT](url)

Think the device model is set correctly, have another 20 or so Cisco SMB devices (SG200/SG300/SG500/SG550) working ok via SSH.

![screen shot 2018-01-16 at 13 37 42](https://user-images.githubusercontent.com/28621135/34991710-772da848-fac2-11e7-8c98-974d5194ce6e.png)

The problem device is my router.db is:

DATA-SW-01:1.2.3.4:ciscosb:username:password:group:8082

Regards,
PK

**Comment by mattie47** [comment] 2018-01-17 00:28
Hi @packetkicker 

OK so oxidized is connecting to the device but not getting past the username prompt.

Rather than use cat, try using VIM to open the log file.  VIM will show if there are any hidden characters such as new lines e.g. /r and spaces e.g. /s. 

I had an issue like this with a space after the login: prompt and solved it in awplus.rb by doing:

```
  #Config required for telnet to detect username prompt
  cfg :telnet do
    username /login:\s/
    end
```

In a test environment, you could try modify ciscosmb.rb and see if this works:

```
-    username /^User ?[nN]ame:/
+    username /^User ?[nN]ame:/s/
```

Or create a new ciscosmb model file with the changes and only assign it to to the SG300 and test that way.

Hopefully that helps.

Thanks,

Matt

**Comment by packetkicker** [comment] 2018-01-17 16:05
Opening the log for this device in vim shows as [~/.config/oxidized/logs/1.2.3.4-ssh](https://pastebin.com/JmX9hVxR)

There are some characters which show in vim but not nano/cat.  These appear to be a backspace and linefeed.

I presume I need to modify the ciscosmb.rb file to account for the special hidden characters?

Thanks for your help so far.

Regards,
PK

**Comment by mattie47** [comment] 2018-01-17 21:11
@packetkicker 

Yes I imagine the best course of action will be to modify ciscosmb.rb to account for this, but also ensure it doesn't break the functionality for pre-existing devices which use this model.

So you have:

```
^[[H^[[JUsername:
```

Perhaps this may help:

| VT100 Esc Code |                   Description                   | Ruby syntax |
|----------------|:-----------------------------------------------:|------------:|
| ^ 			 | Escape character						           | \e          |
| ^[ 			 | Escape character + Control Sequence Introducer  | \e\[        |
| ^M 			 | Carriage Return								   | \r          |
| ^[[7m			 | Reverse SGR7 - Turn reverse video on            | \e\[7m      | 
| ^[[m			 | modesoff SGR0  - Turn off character attributes  | \e\[m       |
| ^[[K	 		 | cleareol EL0   - Clear line from cursor right   | \e[K		 |

I spent some time trying to figure out issues with Allied Telesis products with hidden characters and came up with above. I'd say it's at least 80% correct. 

Maybe try get some ideas from what I did in awplus.rb

Perhaps you could try:

```
username /\e\[b\e\[nUsername:/
```

**Sources**

- http://wiki.bash-hackers.org/scripting/terminalcodes
- https://en.wikibooks.org/wiki/Ruby_Programming/Syntax/Literals
- http://www.uqac.ca/flemieux/PRO100/VT100_Escape_Codes.html
- https://www.csie.ntu.edu.tw/~r92094/c++/VT100.html
- http://www.comptechdoc.org/os/linux/howlinuxworks/linux_hlvt100.html

Thanks,

Matt

**Comment by packetkicker** [comment] 2018-01-18 08:54
I have changed the username line in [cisco.sb](https://pastebin.com/fZqrSeMc) to be as above.

This works ok for the historic devices I had configured though not resolved the problem SG220.  The error message in [/var/log/messages](https://pastebin.com/HYuMsSGG) is now showing 'not matching configured prompt'.

Any pointers on how I should modify the prompt?

Thanks,
PK

**Comment by mattie47** [comment] 2018-01-18 21:01
@packetkicker 

I think the issue is with perhaps the prompt not accounting for the ^[[H^[[J:

```
  prompt /^\r?([\w.@()-]+[#>]\s?)$/
```

I'm really not good at regex sorry :-( 

@ytti  @laf  Any thoughts on what he might need to do to get support for SG220 working? 

His issue is the ciscosmb.rb model file doesn't account for a backspace and linefeed prior to username prompt:

```
^[[H^[[JUsername:
```

Thanks,

Matt

**Comment by mattie47** [comment] 2018-01-18 21:55
Also @packetkicker if you can possibly arrange external SSH access to a sanitized SG220, someone here might be able to have a look and figure out what needs doing. 

Don't post details publicly here though. Let us know if you are able to arrange this. 

Thanks,

Matt

**Comment by packetkicker** [comment] 2018-01-22 09:17
Yes I can arrange access to a switch. Please PM me if anyone is able to help.

Thanks,
PK

**Comment by mattie47** [comment] 2018-01-22 09:34
@packetkicker  flick me an email: my username on Gmail.

I'll have a brief look tomorrow morning

Matt

**Comment by mattie47** [comment] 2018-01-23 01:33
@packetkicker 

Some good news!

After a lot of trial and error, I managed to get in through oxidized.

The pager doesn't need changing, and the end result ended up being very simple:

```
  cfg :telnet, :ssh do
    username /Username:/
    password /Password:/
``` 

Literally that was enable to get in. 

Now there's two options, either make a secondary model just for the SG200 and make this change, or try and modify the username variable to expect either /^User ?[nN]ame:\s/ OR /Username:/

Same with password. Again I don't really know Ruby so don't know what to suggest, but I think I've given you enough to get further with this :-) 

-----------

After getting it to save the config, I have one other model config suggestion:

```
  cmd 'show version' do |cfg|
    cfg = cfg.each_line.to_a[0..-1].join
    cfg.gsub! /^*.(uptime is).*/, '<uptime removed>'
    comment cfg
  end
```

If you don't have that, you won't get meaningful diffs, as it lists the devices uptime in show version. 

With that added, the configuration becomes:

```
 Cisco Sx220 Series Switch Software, Version 1.1.4.1, RELEASE SOFTWARE
! Copyright (c) 2014-2017 by Cisco Systems, Inc.
! Compiled Mon Nov 27 13:21:51 UTC 2017
! 
! ROM: Bootstrap program is Sx220 boot loader
! BOOTLDR: Sx220 Boot Loader Version 1.0.0.6, RELEASE SOFTWARE
! Compiled Jan 24 2014 - 14:43:52
! 
! DATA-SW-01<uptime removed> <---------------------------------------- HERE
! system image is image-2
! 
!  Processor 500MHz , with 128M bytes of memory.
! 26 Gigabit Ethernet interfaces
! 0 Fast Ethernet interfaces
! 
! 32M bytes of flash memory
! Base MAC Address : 2C:AB:EB:CB:D0:53
! IP Address       : 172.16.12.3
! Subnet Mask      : 255.255.255.0
! Model Number     : SG220-26P
! Serial Number    : DNI213606FK
! PID              : SG220-26P-K9
! VID              : V03
config-file-header
DATA-SW-01
v1.1.4.1
CLI v1.0
@
!
!
!
hostname "DATA-SW-01"

```


Thanks,

Matt :-)

**Comment by mattie47** [comment] 2018-01-23 02:18
Perhaps ask if someone has an idea on what to do in the oxidized group chat - https://gitter.im/oxidized/Lobby

**Comment by packetkicker** [comment] 2018-01-23 09:00
Hi Matt,

Great news! Thanks again for looking at this.

I am out the office for most of today so will be tonight before I get a
chance to create a new .rb file and have a play.

Will let you know how I get on.

Regards,
Colin



--
*Colin Copland*
Mob: 07736 272 881

**Comment by mattie47** [comment] 2018-01-31 02:24
>Hi Matt,
>
>I changed the ciscosmb.rb file to include your modifications and it works on the problem SG220 no >problem. Also works on all other Cisco SMB switches I have setup.
>
>Thanks again for your assistance with this very much appreciated.
>
>Regards,
>Colin

Glad you were able to get it working! 

Hopefully someone may be able to have a look at updating https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ciscosmb.rb  however given you're happy it's probably worth closing this issue. 

Thanks,

Matt

**Comment by Atroskelis** [comment] 2018-04-11 11:25
Hello.

Indeed, there's an annoying CLI difference between SG220+ and SG300.

I grinded my neurons vs regex and believe i found a pattern for every possible SG:

Probably could've been optimized, but it's better than nothing. 

` cfg :telnet, :ssh do
    username /(?:(?:Username:)|(?:(?:User\ Name\:))|(?:(?:User\ name\:)))/
    password /(?:(?:Password\:)|(?:(?:password\:)))/`

**Comment by laf** [comment] 2018-04-11 12:39
What are the actual prompts it's trying to match?

**Comment by Atroskelis** [comment] 2018-04-12 08:04
So Oxidized throws out something like this with a SG220 : 

`172.16.31.78 raised Oxidized::PromptUndetect with msg "#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012        Welcome to Layer 2 Managed Switch#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012  Press <Enter> to continue...#015#012#033[H#033[JUsername:  not matching configured prompt (?-mix:^\r?([\w.@()-]+[#>]\s?)$)"`

SG230 tosses some newlines and ultimately shows 

`User Name:`

**Comment by ntokos** [comment] 2020-03-04 08:22
Hello,
so the PR #1473 by @Atroskelis has solved the login issues for SG220 switches that ciscosmb model has.
In order to completely assimilate SG220 switches there also has to be a solution for the uptime string that causes meaningless diffs. Note that the complete removal of `show system` command from the ciscosmb model (by PR #1799) hasn't solved the problem since in SG220 switches the uptime is printed by the `show version` command.
So a further modification of the model code is required, similar to what was suggested by @mattie47 in one of his [comments above](https://github.com/ytti/oxidized/issues/1148#issuecomment-359640123), to something like this:
```ruby
cmd 'show version' do |cfg|
    cfg.gsub! /uptime is\ .+/, '<uptime removed>'
    comment cfg
end
```

**Comment by wk** [comment] 2020-04-25 11:51
Closing this issue as it appears to have been resolved but left open.

**Closed by wk** 2020-04-25 11:51 UTC
Labels: help
