### ISSUE TITLE
Send diffs email

### ISSUE THREAD

**Issue by itscassa** [ytti/oxidized#157] opened 2015-08-07 12:59 UTC
Rancid has the option to send emails with diffs, it would be great if this would be added to oxidized.

**Comment by ytti** [comment] 2015-08-07 13:13
This is likely duplicate of #60 

Personally I'm currently leaving this task to gitlab. Perhaps you can leave it to bitbucket, for now?

**Comment by itscassa** [comment] 2015-08-07 13:20
That's actually a pretty good idea. Will try to find one for Bitbucket.

**Comment by itscassa** [comment] 2015-08-07 13:40
Got it. https://confluence.atlassian.com/display/BITBUCKET/Email+Diff+service+management

**Closed** 2015-08-07 13:40 UTC
