### ISSUE TITLE
When groups are defined Group directory is not created in configs directory

### ISSUE THREAD

**Issue by Alexanderis** [ytti/oxidized#594] opened 2016-10-25 13:05 UTC
```
output:
   default: file
   file:
     directory: /etc/oxidized/configs
```
I have custom groups specified in the router.db file. Instead of creating the folders under /etc/oxidized/configs it creates them under /etc/oxidized/.

Changed oxidized-0.16.3/lib/oxidized/output/file.rb from 
```
    if opt[:group]
      file = File.join File.dirname(file), opt[:group]
    end
```
to 

```
    if opt[:group]
      file = File.join file, opt[:group]
    end

```
and it looks like its creating folders correctly under  /etc/oxidized/configs

**Comment by davama** [comment] 2016-10-25 13:09
I noticed that too with 0.18.0

workaround for me:
`     directory: /home/config/repository/dummydirectory/.`

And this saves configs in `repository` directory.

**Comment by Alexanderis** [comment] 2016-10-25 13:16
```
    file = File.expand_path @cfg.directory
    if opt[:group]
      file = File.join File.dirname(file), opt[:group]
    end
```

I think the root cause is that **File.dirname(file)**  thinks the /etc/oxidized/configs path points to a file and removes the **configs** part, same with your example with **dummydirectory**.

**Comment by ytti** [comment] 2016-10-25 14:00
The intended behaviour is that groups are created one directory below the stated directory, and this is how it has been from day1 AFAIK.

Rationale for this is, we want 'non-group' to be directory also, at the same level as 'group', right? We don't want it to be special case.
Easiest way to achieve this, is to just assume the directory points to non-group directory, and put groups below that.

So correct config indeed is ```directory: /foo/bar/default-groupless```, in which case the groups will be in ```/foo/bar/group1```, all nicely under same /foo/bar directory.

Otherwise we'd need two config options, ```group_root_directory``` and ```groupless_directory``` which does not seem necessary and may be too complicated.

**Closed** 2016-10-25 14:01 UTC

**Comment by Alexanderis** [comment] 2016-10-25 16:07
If this is expected then fetch should take into account the correct path to the config files:
```
oxidized/lib/oxidized/output/file.rb

 def fetch node, group
    cfg_dir = File.expand_path @cfg.directory
    node_name = node.name

 if group # group is explicitly defined by user
      IO.readlines File.join(cfg_dir, group, node_name)  
``` 

^-- this will try to look in /etc/oxidized/configs/GROUP which fails 

`No such file or directory @ rb_sysopen - /etc/oxidized/configs/SJC POD1/co137.sjc.aristanetworks.com
`

**IO.readlines File.join(File.dirname(cfg_dir), group, node_name)** to keep it consistent with what was discussed previously?

**Comment by ytti** [comment] 2016-10-25 16:12
Yes fetch seems broken, pull request is welcome.

**Comment by danilopopeye** [comment] 2016-10-28 13:35
@ytti should we reopen this issue or create another for the `#fetch` problem?

**Comment by ytti** [comment] 2016-10-28 15:23
I fixed the fetch already (I hope) so I think we're good.

**Comment by danilopopeye** [comment] 2016-10-28 16:08
👏

**Comment by davama** [comment] 2016-10-28 17:06
@ytti thanks! 
what PR#?

**Comment by ytti** [comment] 2016-10-28 17:09
there is no PR, it's direct commit because I riding dirty.

```https://github.com/ytti/oxidized/commit/449522554473f4b9a261ec06ee6961defb30f7bb```

**Comment by davama** [comment] 2016-10-28 17:09
hahahaha
nice!

**Comment by davama** [comment] 2016-10-28 17:46
interestingly i did a `gem install oxidized` to reinstall oxidized, with "rouge" commit :P ,  but the file.rb file still has the old code.

**Comment by ytti** [comment] 2016-10-28 17:55
i've not published new gem, 'gem install X' installs latest published one, the change is just in the git. You can manually build gem by saying 'rake build' in the source directory

**Comment by ytti** [comment] 2016-10-28 17:57
The fix isn't about storing them in different place, they are stored in correct place. The fix is fetching them from correct place.

Imagine you have devices without group, and device with group A and group B. How do you want the directory hierarchy be?

Do you want
```
/directory/groupless/groupless-device
/directory/groupless/A/A-device
/directory/groupless/B/B-device
```

Or do you want
```
/directory/groupless/groupless-device
/directory/A/A-device
/directory/B/B-device
```

If you want latter, what is most efficient way to communicate that?

**Comment by davama** [comment] 2016-10-28 18:58
Ohh! misunderstanding then. my bad

Well, in our particular setup we have groups within groups with `/` (which i know is not supported... yet). i was told to submit a PR for it but havent done so.

the sql db file has records as so:
```
ARG-B25-2-AP-1|ios|ARG/WIFI/ARG-B25-2-AP-1
ARG-B24-3TR-SW-1|procurve|ARG/ACCESS/ARG-B24-3TR-SW-1
```

with the config file having `directory: /home/config/repository/.` that would save them in `/home/config/repository/` with the folder `ARG` and all its subdirectories. ( again i know group name with `/` is not supported but it worked so why complain). 
when updated oxidized to 0.18.0 i had to change to `directory: /home/config/repository/dummydirecotry/.` to make it work with the same behavior. (saving files to the `repository` directory)

When i saw @Alexanderis mention

> Instead of creating the folders under /etc/oxidized/configs it creates them under /etc/oxidized/

i thought it was related and not unique to our nested groups, so posted my 2-cents

I'll submit a PR for the group nesting soon. Right now it works using `gem install` with the `dummydirectory` for our needs so I think we good :+1: 

Thank you for your support @ytti
