### ISSUE TITLE
Oxidized throws a Inappropriate ioctl for device [Errno::ENOTTY] when SSH-ing with a HTTP source (librenms)

### ISSUE THREAD

**Issue by Atroskelis** [ytti/oxidized#1277] opened 2018-04-12 08:46 UTC
I've got 2 boxes where the same thing happens.

If i use file source, SSH works, if i use this method, it gives off the error :

```
Inappropriate ioctl for device [Errno::ENOTTY]
--------------------------------------------------
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/prompt.rb:44:in `noecho'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/prompt.rb:44:in `ask'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:53:in `block (2 levels) in authenticate'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:50:in `times'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:50:in `block in authenticate'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:20:in `loop'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:20:in `authenticate'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `each'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh.rb:237:in `start'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/input/ssh.rb:49:in `connect'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/node.rb:65:in `run_input'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/node.rb:42:in `block in run'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/node.rb:37:in `each'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/node.rb:37:in `run'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/job.rb:9:in `block in initialize'
```

telnet seems to work, but it's inconvenient as hell.

Seems to be related to #1130

**Comment by laf** [comment] 2018-04-16 12:39
This is a duplicate of #1130. Closing.

**Closed by laf** 2018-04-16 12:39 UTC
Labels: wontfix
