### ISSUE TITLE
oxidized not show versions

### ISSUE THREAD

**Issue by chenjun-oxidized2020** [ytti/oxidized#2052] opened 2020-03-19 05:00 UTC
[root@localhost oxidized]# systemctl  status oxidized -l
● oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/usr/lib/systemd/system/oxidized.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2020-03-19 00:59:05 EDT; 26s ago
 Main PID: 1915 (oxidized)
   CGroup: /system.slice/oxidized.service
           └─1915 puma 3.11.4 (tcp://127.0.0.1:8888) [/]     

Mar 19 00:59:05 localhost.localdomain oxidized[1915]: * Min threads: 0, max threads: 16
Mar 19 00:59:05 localhost.localdomain oxidized[1915]: * Environment: development
Mar 19 00:59:05 localhost.localdomain oxidized[1915]: * Listening on tcp://127.0.0.1:8888
Mar 19 00:59:05 localhost.localdomain oxidized[1915]: Use Ctrl-C to stop
Mar 19 00:59:06 localhost.localdomain oxidized[1915]: :paranoid is deprecated, please use :verify_host_key. Supported values are exactly the same, only the name of the option has changed.
Mar 19 00:59:06 localhost.localdomain oxidized[1915]: verify_host_key: false is deprecated, use :never
Mar 19 00:59:15 localhost.localdomain oxidized[1915]: :paranoid is deprecated, please use :verify_host_key. Supported values are exactly the same, only the name of the option has changed.
Mar 19 00:59:15 localhost.localdomain oxidized[1915]: verify_host_key: false is deprecated, use :never
Mar 19 00:59:24 localhost.localdomain oxidized[1915]: :paranoid is deprecated, please use :verify_host_key. Supported values are exactly the same, only the name of the option has changed.
Mar 19 00:59:24 localhost.localdomain oxidized[1915]: verify_host_key: false is deprecated, use :never
[root@localhost oxidized]#

**Comment by ytti** [comment] 2020-03-19 06:47
Duplicate of #2051

**Closed by ytti** 2020-03-19 06:47 UTC
Labels: triage
