### ISSUE TITLE
opengear-IM7200 Net::SSH::Exception "could not settle on hmac_client algorithm"

### ISSUE THREAD

**Issue by ertschi** [ytti/oxidized#2432] opened 2021-12-13 12:54 UTC
Hi there,

when i want backup the CLI Config from a opengear Serial-Server Model: IM7216-2-DAC-LR with Firmware: 4.12.1 .
We get follow Error Message:
Dec XX 09:53:01 XXXXXXX oxidized[194403]: 10.xxx.xxx.254 raised Net::SSH::Exception (rescued RuntimeError) with msg "could not settle on hmac_client algorithm"

When i try do connect with a simple ruby script it works. With the same Net::SSH version  net-ssh (6.1.0, 5.2.0) from same Server.
The Oxidized Version is oxidized (0.28.0, 0.26.3)
##################################################################
~$ more sshtest.rb   (simple ruby script)

require 'net/ssh'
require 'net/ssh/proxy/command'
require 'timeout'

Net::SSH.start("10.xxx.xxx.254", "root", password: "PASSWORD") do |ssh|
 result = ssh.exec!("ls -l")
 result = ssh.exec!("config -g config")
 puts result
end
##################################################################
Can anyone give some hint or has idea what we make wrong.
On other Device like Aruba Swichtes or Checkpoint Clish or F5 we has no problems with SSH loggin via ruby.

Thanks

**Comment by mortzu** [comment] 2021-12-15 18:40
We need to update Net::SSH to the actual version in gemspec (and maybe update some code - I don't know if there are any breaking changes)

**Comment by Senetus** [comment] 2022-01-06 15:28
Would be nice to get this sorted, also bumped into it with opengears after an update. The older/weaker cryptos are now disabled on them by default, from 4.11 onwards.

**Comment by mortzu** [comment] 2022-01-12 12:20
duplicate of #2314

**Closed by mortzu** 2022-01-12 12:20 UTC

**Comment by gbbromley** [comment] 2022-07-07 07:39
A workaround for OpenGear products is to edit the file /etc/config/sshd_config and under the line marked "# Opengear Managed Configuration - User Authentication Restrictions" add in the extra MACs, ciphers etc you want. A working minimum would aligning to Mozilla OpenSSH modern hardening would be to add:
Macs +hmac-sha2-256,hmac-sha2-512

Requires SSH daemon to be restarted

**Comment by listerr** [comment] 2022-09-21 08:24
This fixed for me.

However, when the device reboots, or if the sshd config is changed via the Opengear interface, the changes are removed.
(e.g. tick or untick "Disable Password Authentication" in a user profile)

The solution is to create a script on the OG:

`/etc/config/scripts/config-post-sshconfig`

(It must be named as above, then OG will automatically run it whenever sshconfig configurator is run)

```
#!/bin/bash

# Update sshd_config:

FILE=/etc/config/sshd_config

MAC_CONF=`grep -qi "^Macs +hmac-sha2-256,hmac-sha2-512" $FILE`
DO_HACKS=$?

if [[ $DO_HACKS -gt 0 ]] ; then

  # Insert Oxidized workaround for ssh:
  sed -e 's/# Opengear Managed Configuration - User Authentication Restrictions/# Opengear Managed Configuration - User Authentication Restrictions\n# Workaround for oxidized:\nMacs +hmac-sha2-256,hmac-sha2-512\n/' -i $FILE

  # hup sshd:
  kill -HUP `ps -eaf | grep '/bin/sshd' | grep -v grep | awk '{print $2}'`

fi

```

Then to update it when the box reboots:

`/etc/config/rc.local`

```
#!/bin/sh
#
# This script is executed after all the other init scripts, and is where you
# should put any customized startup items you require.
#

# Update sshd_config:
/etc/config/scripts/config-post-sshconfig

```

(Don't forget to give the scripts execute permissions)

**Comment by gbbromley** [comment] 2024-01-23 09:58
For those moving to 5.0.x of the OpenGear codebase on ACM/IM units there have been changes. The file /etc/config/sshd_config.local now holds the user additions to allow SSH configuration adjustments.

An update script that works for 4/5 units is:
```
#!/bin/bash
# Update sshd_config
CONFFILE=/etc/config/sshd_config
MAC_CONF=`grep -qi "^Macs +hmac-sha2-256,hmac-sha2-512" $CONFFILE`
DO_HACKS=$?
if [[ $DO_HACKS == 1 ]]
then
   ACM4X_UNIT=`grep -qi "^# Opengear Managed Configuration" $CONFFILE`
   ACM4X=$?
   if [[ $ACM4X == 0 ]]
   then
     # We are a v4.x unit Insert Oxidized workaround for ssh
     sed -e 's/# Opengear Managed Configuration - User Authentication Restrictions/# Opengear Managed Configuration - User Authentication Restrictions\n# Workaround for ozidized:\nMacs +hmac-sha2-256,hmac-sha2-512\n/' -i $CONFFILE
   else
     # We are a v5.x unit update /etc/config/sshd_config.local
     echo "Macs +hmac-sha2-256,hmac-sha2-512" >/etc/config/sshd_config.local
   fi
   # Restart SSHD
   kill -HUP `ps -eaf | grep '/bin/sshd' | grep -v grep | awk '{print $2}'`
fi
```
