### ISSUE TITLE
oxidized not showing versions

### ISSUE THREAD

**Issue by chenjun-oxidized2020** [ytti/oxidized#2051] opened 2020-03-19 03:33 UTC
prompt： You're seeing this error because you have enabled the show_exceptions setting.

Mar 18 23:26:58 oxidized-network-131 oxidized: /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `each'
Mar 18 23:26:58 oxidized-network-131 oxidized: /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `call'
Mar 18 23:26:58 oxidized-network-131 oxidized: /usr/local/lib/ruby/gems/2.5.0/gems/rack-1.6.13/lib/rack/builder.rb:153:in `call'
Mar 18 23:26:58 oxidized-network-131 oxidized: /usr/local/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
Mar 18 23:26:58 oxidized-network-131 oxidized: /usr/local/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
Mar 18 23:26:58 oxidized-network-131 oxidized: /usr/local/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
Mar 18 23:26:58 oxidized-network-131 oxidized: /usr/local/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
Mar 18 23:26:58 oxidized-network-131 oxidized: /usr/local/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Mar 18 23:32:50 oxidized-network-131 systemd: Started Session 30 of user root.
Mar 18 23:32:50 oxidized-network-131 systemd-logind: New session 30 of user root.

**Comment by ytti** [comment] 2020-03-19 06:47
Duplicate of #2049

**Closed** 2020-03-19 06:47 UTC
Labels: triage
