### ISSUE TITLE
Problem with pfsense.rb device

### ISSUE THREAD

**Issue by Aanistratenko1984** [ytti/oxidized#3325] opened 2024-11-21 08:37 UTC
We use PfSense device.
Default model file lib/oxidized/model/pfsense.rb not working with errors.
So we corrected it 
1. Comment  Refinements `# using Refinements`
2. change `xmlcomment "PFsense #{version}"` to `comment "PFsense #{version}"`

After changer working well.

**Comment by robertcheramy** [comment] 2024-11-29 20:11
The pfsense model works as it is. If the correction works for you, fine.
Closing the issue.

**Closed by robertcheramy** 2024-11-29 20:11 UTC

**Comment by robertcheramy** [comment] 2024-12-03 21:47
This was quite a harsh comment from me, sorry for this. Removing Refinements is not the solution, as they are needed by every model.
I have reopened Issue #3109 and will work on the problem there.
I'm keeping this issue closed as it is a duplicate of #3109
