### ISSUE TITLE
add linux/arm64/v8 to docker file

### ISSUE THREAD

**Issue by murraythegoz** [ytti/oxidized#2977] opened 2023-10-30 10:12 UTC
The above arch is not avail.
Please add it to the supported architecture to enable automatic deployment/upgrade on arm64.

TIA

**Comment by aschaber1** [comment] 2023-10-30 12:04
Hello @murraythegoz , sounds like a good idea. I'll have a go at it possibly next week.

**Comment by aschaber1** [comment] 2023-10-30 13:06
Duplicate of #2910.

**Closed by aschaber1** 2023-10-30 13:06 UTC
