### ISSUE TITLE
disconnected: protocol error: rcvd type 0

### ISSUE THREAD

**Issue by kevhjelm** [ytti/oxidized#1715] opened 2019-02-26 14:26 UTC
When trying to get the config of VSP9K, I'm getting this error: 
disconnected: protocol error: rcvd type 0
What does it mean? Below is the debug
How can I solve it?
![image](https://user-images.githubusercontent.com/41345256/53419603-75971480-39da-11e9-80e2-fc15eeba1e91.png)

**Comment by wk** [comment] 2019-03-03 20:21
Which version of OpenSSL does the underlying linux distribution use?

**Comment by kevhjelm** [comment] 2019-03-04 07:09
Doing _openssl version_ outputs: 
OpenSSL 1.1.0g  2 Nov 2017
another error that keep poping up is:

![image](https://user-images.githubusercontent.com/41345256/53716176-570aa080-3e54-11e9-9dc0-0ff8b4ef91d5.png)

I've tried to start the ssh-agent doing : _eval `ssh-agent`_
but still fails with the same error, is it anything that i've missed?
Non of the other devices has this problem, only my last 10 switches. They are Extreme network switches VSP8K and VSP9Ks

**Comment by wk** [comment] 2019-03-06 19:26
Closing this as duplicate of #1724.

**Closed by wk** 2019-03-06 19:26 UTC
