### ISSUE TITLE
Adtran model causing misreporting and config failure

### ISSUE THREAD

**Issue by MajesticFalcon** [ytti/oxidized#2561] opened 2022-06-08 18:49 UTC
When I remove "cmd vars(:enable)" from the adtran.rb model, all works fine. However, the current state of the model gives me the error below. Also notice how the job believes the configuration to be fetched, likely because the SSH was sucsessful in getting some commands sent.

I am not sure if this impacts others or just me so I won't create a pull request just yet. 

![image](https://user-images.githubusercontent.com/8593209/172693484-cae10a24-a54c-4bf9-a7c6-4d4482dd7e9e.png)

**Comment by andrewohanian** [comment] 2022-06-15 03:22
I had the same issue, and did the same workaround as you.

**Comment by mgob** [comment] 2022-12-29 20:49
Dupe of #2553

**Closed** 2022-12-30 17:52 UTC
