### ISSUE TITLE
Abort job if configuration file contain some text

### ISSUE THREAD

**Issue by andrejzverev** [ytti/oxidized#2383] opened 2021-10-13 10:25 UTC
Hello, i have question of how correct to solve issue. Sometimes, when gathering configuration our external TACACS server is moved into down state and commands return "authorization error". I want somehow to detect error (text in cfg) in result config and if found abort job (don't save config) and try next time. Curretly broken config override last good one.

**Comment by mortzu** [comment] 2022-01-12 16:07
Duplicate of #2114

**Closed by mortzu** 2022-01-12 16:07 UTC
