### ISSUE TITLE
External git repository

### ISSUE THREAD

**Issue by darkounet** [ytti/oxidized#141] opened 2015-06-25 09:06 UTC
It is possible or plan to use an external git repository ( i.e.: Gitlab / Github / ... )

**Comment by ytti** [comment] 2015-06-25 09:10
No, but we have plan in #60. For now just use crontab job.

I don't think anyone wants to use external repo directly, since what happens if it's offline? Having local repo guarantees we can commit. But I personally only use the local repo as interim, and push periodically to gitlab.

Closed as duplicate of #60

**Closed by ytti** 2015-06-25 09:10 UTC
