### ISSUE TITLE
Output: git, file (Not working)

### ISSUE THREAD

**Issue by unlimitedskills** [ytti/oxidized#1330] opened 2018-05-04 00:43 UTC
This works...
output:
  default: file
  git:
    user: oxidized
    email: oxidized@somewhere.com
    repo: "/home/oxidized/.config/oxidized/oxidized.git/"
  file:
    directory: /home/oxidized/.config/oxidized/configs/

This works....
output:
  default: git
  git:
    user: oxidized
    email: oxidized@somehere.com
    repo: "/home/oxidized/.config/oxidized/oxidized.git/"
  file:
    directory: /home/oxidized/.config/oxidized/configs/

This does not work... Oxidized fails to start
output:
  default: git, file
  git:
    user: oxidized
    email: oxidized@somewhere.com
    repo: "/home/oxidized/.config/oxidized/oxidized.git/"
  file:
    directory: /home/oxidized/.config/oxidized/configs/

**Comment by wk** [comment] 2018-05-04 01:39
Duplicate of #425

**Closed by wk** 2018-05-04 01:39 UTC
Labels: duplicate
