### ISSUE TITLE
Procurve 

### ISSUE THREAD

**Issue by lwhitworth** [ytti/oxidized#401] opened 2016-04-20 14:01 UTC
I am testing Oxidized with a couple of HP switches I have lying around (one 2920, one 2610).  The 2920 works fine every time, the 2610 though throws the error:
`xxx.xxx.xxx.xxx raised Oxidized::PromptUndetect with msg "[1;1Hmy-switch#  not matching configured prompt (?-mix:^\r?([\w -]+\eE)?([\w-]+# )$)"`
However, if I reboot the 2610 and immediately run Oxidized against it it works fine.  If I reboot, SSH into the switch, logout and then try to run Oxidized it fails with the same message.

Looking at the debug log for the ssh connection on a successful run it appears that the lines for the prompt are different, e.g:  `[24;1Hmy-switch#`.  I've tried to look at the procurve definition but my ruby isn't that great, could it be that `expect /\e\[\??\d+(;\d+)*[A-Za-z]/ do |data, re|` isn't matching the [1;1 but happy with the [24;1?

**Comment by lwhitworth** [comment] 2016-04-20 14:50
Looking into the output a bit more from that switch I see:

```
^[[1;24r^[[24;14H^[[2J^[[?7l^[[1;24r^[[?6l^[[24;14H^[[?25h^[[24;14H^[[?6l^[[1;0r^[[?7l^[[2J^[[24;14H^[[1;1H^[[2K^[[24;14H^[[2J^[[?7l^[[3;23r^[[?6l^[[1;1H^[[?25l^[[1;1HProCurve J9085A Switch 2610-24^M
^MSoftware revision R.11.112^M
^M^M
^MCopyright (C) 1991-2015 Hewlett-Packard Co.  All Rights Reserved.
^M
^M                           RESTRICTED RIGHTS LEGEND
^M
^M Use, duplication, or disclosure by the Government is subject to restrictions
^M as set forth in subdivision (b) (3) (ii) of the Rights in Technical Data and
^M Computer Software clause at 52.227-7013.
^M
^M         HEWLETT-PACKARD COMPANY, 3000 Hanover St., Palo Alto, CA 94303
^M
^M^[[24;1HPress any key to continue^[[1;1H^[[?25h^[[24;27H^[[2J^[[?7l^[[3;23r^[[?6l^[[24;27H^[[?25h^[[24;27H^[[?6l^[[1;24r^[[?7l^[[2J^[[24;27H^[[1;24r^[[24;27H^[[2J^[[?7l^[[1;24r^[[?6l^[[24;1H^[[1;24r^[[24;1H^[[24;1H^[[2K^[[24;1H^[[?25h^[[24;1H^[[24;1Hmy-switch# ^[[24;1H^[[24;14H^[[24;1H^[[?25h^[[24;14H
```

Just a hunch, but could ^[[?25l^**[[1;1HP**roCurve J9085A Switch be the issue here?  All the other ANSI characters seems to be of a different form that includes a letter and ^, this one doesn't?

**Comment by lwhitworth** [comment] 2016-04-20 15:00
Ignore that, just captured the output of a working one and that trait exists in both.  Comparing the two outputs (ignoring lines that are added after it starts working) I get:

```
$ diff noworky worky 
1c1
< ^[[1;24r^[[24;14H^[[2J^[[?7l^[[1;24r^[[?6l^[[24;14H^[[?25h^[[24;14H^[[?6l^[[1;0r^[[?7l^[[2J^[[24;14H^[[1;1H^[[2K^[[24;14H^[[2J^[[?7l^[[3;23r^[[?6l^[[1;1H^[[?25l^[[1;1HProCurve J9085A Switch 2610-24^M
---
> [[2J^[[?7l^[[3;23r^[[?6l^[[1;1H^[[?25l^[[1;1HProCurve J9085A Switch 2610-24^M
13a14,16
> ^MSystem went down:  04/20/16 15:55:46^M
> ^MSaved crash information:^M
> ^MOperator reboot from TELNET session.^M
```

**Comment by ytti** [comment] 2016-04-20 17:32
What does the session look like when you manually connect?

**Comment by lwhitworth** [comment] 2016-04-25 08:07
Apologies for the delay in replying.

Looks normal to my eyes when I connect manually (connecting via SSH).  Get three screens:

```
We'd like to keep you up to date about:
  * Software feature updates
  * New product announcements
  * Special events

Please register your products now at:  www.ProCurve.com

manager@my-switch's password: 
```
```
ProCurve J9085A Switch 2610-24
Software revision R.11.114

Copyright (C) 1991-2015 Hewlett-Packard Co.  All Rights Reserved.

                           RESTRICTED RIGHTS LEGEND

 Use, duplication, or disclosure by the Government is subject to restrictions
 as set forth in subdivision (b) (3) (ii) of the Rights in Technical Data and
 Computer Software clause at 52.227-7013.

         HEWLETT-PACKARD COMPANY, 3000 Hanover St., Palo Alto, CA 94303











Press any key to continue
```
`my-switch# `

**Comment by ytti** [comment] 2016-05-05 13:06
I don't have access to any procurve switch, maybe @Ultra2D can chime in?

If not, is it possible to setup one switch for testing purposes, which I can access?

**Comment by Ultra2D** [comment] 2016-05-06 09:35
Sure. I do have access to the 2610, and oxidized works fine.

Differences I noticed on my switches:

- not the latest firmware (R.11.107), shame on me
- the motd banner is a lot shorter
- no "Press any key to continue" when logging on manually, maybe due to older firmware
- slightly different prompt (no multiline): `prompt /^\r?([\w -]+\eE)?([\w-]+# )$/`

@lwhitworth did you alter the prompt?

I will upgrade one of the switches to the latest firmware and see what happens.

**Comment by lwhitworth** [comment] 2016-05-06 10:30
I didn't modify the prompt no.  Be interested to hear your results, as I said I've only hit it on this one switch model so far, the 2920 I tried works fine.  When I get a few moments I'll see if I can find another 2610 and see if it exhibits the same issue.

**Comment by Ultra2D** [comment] 2016-05-06 10:32
Still works with R.11.112 on first and second try after reloading the new f/w. I did get "Press any key to continue" once when logging on manually (before running oxidized manually). So the error on your end might be caused by the different prompt or the longer motd banner.

F/w R.11.116 is available. will test that now.

I am running oxidized version 0.14.0 btw.

**Comment by lwhitworth** [comment] 2016-05-06 10:44
Okay I'll give it another go on the switch here soonish and see what I can
see.  Just to confirm were you accessing via ssh or telnet?  I've been
using ssh.

**Comment by Ultra2D** [comment] 2016-05-06 11:02
I'm using SSH too.

After upgrading to R.11.116 I can't log on remotely any more (and I am not in the office), so be warned.

**Comment by Ultra2D** [comment] 2016-05-06 14:33
R.11.116 also works. Apparently, from this version on you need to use the correct username when logging on. It did reboot automatically after uploading the firmware image.

**Comment by lwhitworth** [comment] 2016-05-09 15:25
Confusion abounds.  I've reset the switch back to factory settings using the trusty paperclip method, I've then kept the configuration as minimal as possible, so all I've done is run:

```
config
crypto key generate ssh
ip ssh
```
So I've not set a password, so the line in my router.db is purely:
`switch-name:procurve:manager:`

My config is:
```
---
interval: 10
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
rest: 127.0.0.1:8888
vars: {}
groups: {}
input:
  default: ssh
  debug: true
  ssh:
    secure: true
output:
  default: file
  file:
    directory: "/root/.config/oxidized/deviceconfigs"
source:
  default: csv
  csv:
    file: /root/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
model_map:
  cisco: ios
  juniper: junos
  fortigate: fortios
```
I'm using 0.14.1 but still seeing:
`W, [2016-05-09T16:17:45.109966 #3700]  WARN -- : xxx.xxx.xxx.xxx raised Oxidized::PromptUndetect with msg "[1;1HProCurve Switch 2610-24#  not matching configured prompt (?-mix:^\r?([\w -]+\eE)?([\w-]+# )$)"`

Can't get you access to the switch sadly, is there anything else I can try?

**Comment by lwhitworth** [comment] 2016-05-09 15:26
That's also running latest firmare too:
`J9085A Configuration Editor; Created on release #R.11.116`

**Comment by lwhitworth** [comment] 2016-05-09 16:09
Just picked another couple of random 2610s we have on the network (which are running 11.107 and 11.72) and I'm seeing the same error:

`WARN -- : xxx.xxx.xxx.xxx raised Oxidized::PromptUndetect with msg "[1;1Hswitch-2#  not matching configured prompt (?-mix:^\r?([\w -]+\eE)?([\w-]+# )$)"`

`WARN -- : xxx.xxx.xxx.xxx raised Oxidized::PromptUndetect with msg "1;1Hswitch-3#  not matching configured prompt (?-mix:^\r?([\w -]+\eE)?([\w-]+# )$)"`

So certainly not isolated to just one switch :(

**Comment by Ultra2D** [comment] 2016-05-09 17:15
I don't think I have a spare 2610 to test with a default config, so we might have to work backwards. Have you tried changing the motd banner to one or two lines? It's no more than a hunch, but that's all I've got at the moment. The diff you posted earlier did not provide a clue (to me at least).

**Comment by lwhitworth** [comment] 2016-05-11 13:56
Okay, certainly getting somewhere now.  It appears that the following works quite happy:

```
switch(config)# banner motd %
Enter TEXT message.  End with the character'%'
 bob
 %
```
as does
```
switch(config)# banner motd %
Enter TEXT message.  End with the character'%'
 bob%
```
However, running:
`cclw-switch(config)# no banner motd`
which reinstates the default HP welcome text 
```
ProCurve J9085A Switch 2610-24
Software revision R.11.116

Copyright (C) 1991-2016 Hewlett-Packard Co.  All Rights Reserved.

                           RESTRICTED RIGHTS LEGEND

 Use, duplication, or disclosure by the Government is subject to restrictions
 as set forth in subdivision (b) (3) (ii) of the Rights in Technical Data and
 Computer Software clause at 52.227-7013.

         HEWLETT-PACKARD COMPANY, 3000 Hanover St., Palo Alto, CA 94303











Press any key to continue

```
promptly causes it to start failing again with
`xxx.xxx.xxx.xxx raised Oxidized::PromptUndetect with msg "[1;1Hswitch#  not matc"`
So certinaly think we've found the culprit!  Are you able to see if you can replicate?

Cheers for the help, appreciated

**Comment by Ultra2D** [comment] 2016-05-12 10:14
It is still running fine after `no banner motd`. That's odd. I will take a closer look soon.

**Comment by lwhitworth** [comment] 2016-05-12 13:07
Cheers.  I've acutally got my hands on a 2610 that's exhibiting the same issue.  I'll get it up and accessible tonight and send you connection specifics for you to give it a test

**Comment by lwhitworth** [comment] 2016-05-12 16:52
Okay I've got the host up and it should be available. How do you want me to send you the access details?

**Comment by Ultra2D** [comment] 2016-05-12 18:44
It actually was @ytti who asked for access to a test switch. I am not really comfortable with debugging Oxidized on someone else's hardware remotely. If @ytti wants to take a look, that would be great. Otherwise I will put some more effort into reproducing the issue on hardware in my own environment.

**Comment by ytti** [comment] 2016-05-12 18:55
Yes I'm happy to. Please send email to saku@ytti.fi with auth details. It might be weekend before I have time to look into it.

**Comment by lwhitworth** [comment] 2016-05-12 21:26
Email sent :)

**Comment by ytti** [comment] 2016-05-14 10:16
This works fine before changes introduced by @Ultra2D 

If you copy this version to ~/.config/oxidized/model
https://raw.githubusercontent.com/ytti/oxidized/9be5cb4bccad0fcc6fd0b6ab7779cc361fa27620/lib/oxidized/model/procurve.rb

And rerun, you should see configs.


The main issue seems to be, that @Ultra2D changes do not clean all ansi codes, so that the prompt is obstructed by ansi codes.

So we have two options:

a) @Ultra2D looks into this and adapts his changes so that they work on @lwhitworth's device as well
b) we rollback the changes

**Comment by Ultra2D** [comment] 2016-05-14 10:58
Did you happen to capture the ansi codes that were not filtered? That is to say, after https://github.com/ytti/oxidized/blob/4848ddb3237bcd6f01cefcda04cddfa3be2e328f/lib/oxidized/model/procurve.rb#L10 ?

**Comment by ytti** [comment] 2016-05-14 11:16
Nope. But I'm sure @lwhitworth will share access, it's sanitised device containing 0 privileged information.

**Comment by lwhitworth** [comment] 2016-05-14 11:30
Sure thing, send me your email and I'll send you connection details. Cheers for your efforts

**Comment by Ultra2D** [comment] 2016-05-14 13:42
It's my github username @gmail.com. I will test with a fresh oxidized install.

**Comment by lwhitworth** [comment] 2016-05-14 17:19
Cheers, email sent

**Comment by Ultra2D** [comment] 2016-05-14 20:17
It is caused by a line break in the middle of a control sequence, right after "Press any key to continue". The 2610's are not the exact same part number, so the problem only occurs on 2610's without PoE which I don't manage.

I added `Oxidized.logger.debug "shell_open:  #{data.inspect} "` to shell_open in ssh.rb:
```
D, [2016-05-14T21:17:49.602628 #14292] DEBUG -- : shell_open:  "\e[2J\e[?7l\e[3;23r\e[?6l\e[1;1H" 
D, [2016-05-14T21:17:49.612610 #14292] DEBUG -- : shell_open:  "\e[?25l\e[1;1HProCurve J9088A Switch 2610-48\r\n\rSoftware revision R.11.116\r\n\r\r\n\rCopyright (C) 1991-2016 Hewlett-Packard Co.  All Rights Reserved.\n\r\n\r                           RESTRICTED RIGHTS LEGEND\n\r\n\r Use, duplication, or disclosure by the Government is subject to restrictions\n\r as set forth in subdivision (b) (3) (ii) of the Rights in Technical Data and\n\r Computer Software clause at 52.227-7013.\n\r\n\r         HEWLETT-PACKARD COMPANY, 3000 Hanover St., Palo Alto, CA 94303\n\r\n\r\e[24;1HPress any key to continue\e" 
D, [2016-05-14T21:17:49.622903 #14292] DEBUG -- : shell_open:  "[1;1H\e[?25h\e[24;27H" 
D, [2016-05-14T21:17:49.831892 #14292] DEBUG -- : shell_open:  "\e[2J\e[?7l\e[3;23r\e[?6l\e[24;27H" 
D, [2016-05-14T21:17:50.043648 #14292] DEBUG -- : shell_open:  "\e[?25h\e[24;27H\e[?6l\e[1;24r\e[?7l\e[2J\e[24;27H\e[1;24r\e[24;27H" 
D, [2016-05-14T21:17:50.050547 #14292] DEBUG -- : shell_open:  "\e[2J\e[?7l\e[1;24r\e[?6l\e[24;1H" 
D, [2016-05-14T21:17:50.057267 #14292] DEBUG -- : shell_open:  "\e[1;24r\e[24;1H\e[24;1H\e[2K\e[24;1H\e[?25h\e[24;1H\e[24;1Hswitch1# \e[24;1H\e[24;10H\e[24;1H\e[?25h\e[24;10H"
```

`Press any key to continue\e` at the end of the second line is the killer part.

Working 2610:
```
D, [2016-05-14T21:29:51.066596 #1935] DEBUG -- : shell_open:  "\e[2J\e[?7l\e[3;23r\e[?6l\e[1;1H" 
D, [2016-05-14T21:29:51.071681 #1935] DEBUG -- : shell_open:  "\e[?25l\e[1;1HProCurve J9086A Switch 2610-24/12PWR\r\n\rSoftware revision R.11.116\r\n\r\r\n\rCopyright (C) 1991-2016 Hewlett-Packard Co.  All Rights Reserved.\n\r\n\r                           RESTRICTED RIGHTS LEGEND\n\r\n\r Use, duplication, or disclosure by the Government is subject to restrictions\n\r as set forth in subdivision (b) (3) (ii) of the Rights in Technical Data and\n\r Computer Software clause at 52.227-7013.\n\r\n\r         HEWLETT-PACKARD COMPANY, 3000 Hanover St., Palo Alto, CA 94303\n\r\n\r\e[24;1HPress any key to con" 
D, [2016-05-14T21:29:51.079298 #1935] DEBUG -- : shell_open:  "tinue\e[1;1H\e[?25h\e[24;27H" 
D, [2016-05-14T21:29:51.286570 #1935] DEBUG -- : shell_open:  "\e[2J\e[?7l\e[3;23r\e[?6l\e[24;27H" 
D, [2016-05-14T21:29:51.292460 #1935] DEBUG -- : shell_open:  "\e[?25h\e[24;27H\e[?6l\e[1;24r\e[?7l\e[2J\e[24;27H\e[1;24r\e[24;27H" 
D, [2016-05-14T21:29:51.498852 #1935] DEBUG -- : shell_open:  "\e[2J\e[?7l\e[1;24r\e[?6l\e[24;1H" 
D, [2016-05-14T21:29:51.504833 #1935] DEBUG -- : shell_open:  "\e[1;24r\e[24;1H\e[24;1H\e[2K\e[24;1H\e[?25h\e[24;1H\e[24;1Hworkingswitch# \e[24;1H\e[24;10H\e[24;1H\e[?25h\e[24;10H" 
```

I don't quite have my head wrapped around it yet (not familiar with ruby), but I think the lines are appended until a match is found, which is "Press any key to continue". The trailing escape character is lost, and the output buffer is emptied. The next line is missing an escape character, so the second part of the control sequence cannot be filtered.

I don't see an easy and reliable way to fix this. Any suggestions @ytti? 
Another option would be to require people to change the motd banner.

**Comment by ytti** [comment] 2016-05-14 22:53
The two regexp in the original ':all' seem to work, is there some particular issue in them?

**Comment by Ultra2D** [comment] 2016-05-15 09:17
I don't understand, those are not used for prompt detection? 
Anyway, just checked: control sequences are not used within the output (did not know that). In ':all' the output is joined first, so the SSH/shell line breaking is undone (as far as I understand).

**Comment by Ultra2D** [comment] 2016-05-15 09:48
Or maybe your point is that the same (i.e. join lines and split them according to actual new line characters) could be done for everything including login? That would solve the original issue.

**Comment by ytti** [comment] 2016-05-15 13:38
Yeah, you're right, with just :all the prompt detection will remain much unsafer. But perhaps similar logic as in :all in the expect might do the trick?

**Comment by Ultra2D** [comment] 2016-05-17 10:56
We are actually still talking about the old :all, right? Because the current :all had that logic remove (by me).

As far as I understand (and I am having a hard time ;))  `expect` runs on each line of the input (i.e. SSH). How can that be converted to run at each buffered line (as in the old :all), and also work during shell login ( https://github.com/ytti/oxidized/blob/979e6e7260e66c8fecabd6f424e166ba1193f54c/lib/oxidized/input/ssh.rb#L44 )? Is it possible to do this just for procurve.rb? I am hoping you have a better grasp on the inner workings of it all.

**Comment by ytti** [comment] 2016-05-17 11:38
The expects are handled here: https://github.com/ytti/oxidized/blob/979e6e7260e66c8fecabd6f424e166ba1193f54c/lib/oxidized/input/ssh.rb#L93

They are not per-line, but called every time we get 'on_data' call-back from ssh library. Of course you can force expect to be per line, by matching $ in regexp, indicating end-of-line, this way the expect won't match on partial lines.

**Comment by Ultra2D** [comment] 2016-05-17 12:00
That's what I tried to describe, and failed. Thanks for putting it more clearly.

The $ will match end of data, which is not necessarily end of line, right?
What would happen if you moved https://github.com/ytti/oxidized/blob/979e6e7260e66c8fecabd6f424e166ba1193f54c/lib/oxidized/input/ssh.rb#L93 one line down, below end? Wouldn't that work? Right now it is running expect too soon (in one very specific case).

**Comment by ytti** [comment] 2016-05-17 12:08
$ is end of line.

If you move it out from on_data call-back, then it won't be called at all when data is received. The 'on_call' block is registering callback to the ssh library, the code isn't specifically even ran there, anything outside the block won't be ran during data received.

What is the specific case? What do you think moving it out from block might have accomplished? It would not have guaranteed that we've read to end of line, on_data does not guarantee that once it returns it has read end of line.
There is no guarantee given SSH interface ever has >1 line, so making that guarantee would break anything which does not always terminate line.

**Comment by Ultra2D** [comment] 2016-05-17 12:58
Well, I disagree, $ is the end of the regular expression. With end of line I mean \n and/or \r. In my understanding $ will match the end of the latest piece of data returned by SSH (after each line of https://github.com/ytti/oxidized/issues/401#issuecomment-219249381 for example).

The specific case is `Press any key to continue\e` (see the same comment). expect runs immediately after receiving that data, which leaves the second part of the control sequence for the next expect (which causes it to fail). Adding a $ will not alter that behaviour imho. I might be able to test my assumptions this evening if @lwhitworth has not disconnected the switch.

My thought behind moving it out of the block is that expect would only run after all data has been received, and not prematurely in the specific case. But you're saying it will never leave the block in normal circumstances?

**Comment by ytti** [comment] 2016-05-17 13:36
You could make it \n$?

**Comment by Ultra2D** [comment] 2016-05-17 19:03
The following seems to work:
```
expect /Press any key to continue(\e\[\??\d+(;\d+)*[A-Za-z])*$/
```
Not too ugly?

**Comment by ytti** [comment] 2016-05-17 20:11
I would really prefer generic solution expect /blaa\n$/ like. But if that cannot be made work, I don't really mind, as long as both you and @lwhitworth are happy with end result.

**Comment by lwhitworth** [comment] 2016-05-17 20:13
As long as it works I'm happy ;)

**Comment by Ultra2D** [comment] 2016-05-17 20:39
There is no \n, only control sequences, so this is the only way I can think of.

**Comment by ytti** [comment] 2016-05-17 20:57
Surely there is \n eventually. Otherwise config would be single line.

**Comment by Ultra2D** [comment] 2016-05-17 21:31
Ah, I mean there is no \n until after a key has been pressed after the  'Press any key to continue' message.

**Comment by admlko** [comment] 2016-07-13 08:02
@Ultra2D 
I still have issues with Procurves, happened with previous version and also with newest version of Oxidized.
So it seems to get extra ";1H" or "[1;1H" as a prefix for hostname and fails because of that.
`D, [2016-07-13T10:05:58.746405 #20517] DEBUG -- : lib/oxidized/input/ssh.rb: expecting /^\r?([\w -]+\eE)?([\w.-]+# )$/ at HOSTNAME
W, [2016-07-13T10:06:18.747439 #20517]  WARN -- : IPADDRESS raised Oxidized::PromptUndetect with msg ";1HHOSTNAME#  not matching configured prompt (?-mix:^\r?([\w -]+\eE)?([\w.-]+# )$)"
`
and

`D, [2016-07-13T09:44:03.801154 #10276] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2016-07-13T09:44:04.125246 #10276]  WARN -- : IPADDRESS raised Oxidized::PromptUndetect with msg "[1;1HHOSTNAME#  not matching configured prompt (?-mix:^\r?([\w -]+\eE)?([\w.-]+# )$)"`

It doesn't seem to be software version related, as other switches with same model and software works, but some fails.

**Comment by Ultra2D** [comment] 2016-07-13 13:56
Right, the fix has not been added to Oxidized. I suppose that would be up to me. Sorry about that.

For now, can you check if it does work when overriding /var/lib/gems/2.1.0/gems/oxidized-0.15.0/lib/oxidized/model/procurve.rb ?
Copy that file to ~/.config/oxidized/model/ and then edit it.

Change
```
  expect /Press any key to continue/ do
```
to
```
  expect /Press any key to continue(\e\[\??\d+(;\d+)*[A-Za-z])*$/ do
```

**Comment by admlko** [comment] 2016-07-14 05:17
Oh yeah, sorry. I didn't check if the fix has been implemented yet to the code base.

But thanks for the instructions, seems to work perfectly! :+1:

**Closed** 2016-08-29 14:54 UTC
