### ISSUE TITLE
Can oxidized support other encoding?

### ISSUE THREAD

**Issue by sseaky** [ytti/oxidized#2411] opened 2021-11-30 08:20 UTC
There are some chinese characters in my device config, which is encoded with gb2312., and the oxidized read config from device using utf8, hence the chinese characters can not be recognized. 
I also found a globle set "utf8_encoded: true" in the file "~/.config/oxidized/config". Is there any way to specify the encoding individually for each device?

**Comment by mortzu** [comment] 2022-01-12 16:19
Duplicate of #2008

**Closed by mortzu** 2022-01-12 16:19 UTC
