### ISSUE TITLE
Init Script

### ISSUE THREAD

**Issue by sts** [ytti/oxidized#72] opened 2015-02-05 12:37 UTC
There is no way to automatically start oxidized and keep it running. What is the proposed way to do this?

**Comment by ytti** [comment] 2015-02-05 13:10
duplicate of #45

**Closed by ytti** 2015-02-05 13:10 UTC

**Comment by sts** [comment] 2015-02-05 14:37
Is Ubuntu the only supported platform (=> upstart)? Other systems are using SysV init or systemd.

**Comment by ytti** [comment] 2015-02-05 19:03
Not at all, this is why #45 is still unresolved. We need more complete solution. I'm not sure what it is. One would be just to include various init scripts in the package and let users copy them.
