### ISSUE TITLE
Incorrect commits

### ISSUE THREAD

**Issue by filenox** [ytti/oxidized#97] opened 2015-03-30 08:12 UTC
-vlann 115 802.1q 3/47 "TAG for VoIP"
+vlan 115 802.1q 3/47 "TAG for VoIP"

While nothing changed on the switch.

**Comment by ytti** [comment] 2015-03-30 08:29
Which model? Did you make typo on your report? There is 'vlann' and 'vlan'?

If that is just typo, I'm guessing there is good chance there is some whitespace difference at end of line. Can you view the two revisions in 'vim' or or such, which would show whitespace differences.

**Comment by filenox** [comment] 2015-03-30 08:45
Alcatel-Lucent OmniSwitch 6000. It's not a typo since nobody (except Oxidized) logged in on the switch.

**Comment by ytti** [comment] 2015-03-30 15:22
aos7 or aos? So your problem is, somewhere spurious 'n' character came and went away?

Are there any non-printable characters differences in the lines, in addition to the 'n' character?

**Comment by filenox** [comment] 2015-03-31 06:51
Version 6.4.4.707.R01.

No, not that I can think of? http://imgur.com/A7zJvVD

**Comment by ytti** [comment] 2015-03-31 15:41
There is absolutely nothing done to the output in 'aos' model:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/aos.rb#L25

So quite surprised at the 'vlann'.

Are you collecting via SSH or telnet?
Can you reproduce the issue?
Does it happen often?
Does it only happen with 'vlan' word, nothing else?

**Comment by filenox** [comment] 2015-03-31 16:54
It doesn't make any sense, I know. Oxidized uses SSH and I cant reproduce the issue, it only happend once so I might think this is a glitch in AOS...

**Comment by ytti** [comment] 2015-03-31 16:58
I guess we have to close this as unable reproduce. However, it's still good it exists, because if this happens again, and it happens on some other node we know something sketchy with Oxidized. If it happens again, and on aos, I guess we can determine most likely just aos specific issue. Even more interestingly if it happens again, and another word, is it again last character duplicated?

**Closed by ytti** 2015-03-31 16:58 UTC
