### ISSUE TITLE
oxidized not showing versions，SOS

### ISSUE THREAD

**Issue by chenjun-oxidized2020** [ytti/oxidized#2053] opened 2020-03-19 09:18 UTC
WEB：（Version）
![image](https://user-images.githubusercontent.com/60096209/77050876-5adc7700-6a05-11ea-8c0c-0402fb0c4f82.png)
tail -f /var/log/message:
![image](https://user-images.githubusercontent.com/60096209/77050955-7ba4cc80-6a05-11ea-9415-97df69d0315e.png)
Oxidized version:
![image](https://user-images.githubusercontent.com/60096209/77050981-86f7f800-6a05-11ea-9fd1-840da321160e.png)

How to solve this problem, please help, thank you very much

**Comment by chenjun-oxidized2020** [comment] 2020-03-19 09:21
My config is

---
username: username 
password: password
model: junos
resolve_dns: true
interval: 7200
log: /root/.config/oxidized/logs/oxidized.log
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups:
  HLBD-C1-5FB-Core:
    username: admin
    password: Core@Shizhuang2020.. 
  HLBD-C1-4&5F-Poe:
    username: admin
    password: Poe@Shizhuang2020..
  HLBD-C1-4&5F-Access:
    username: admin
    password: Access@Shizhuang2020..
  HLBD-C1-5F-WLC:
    username: admin
    password: WLC@Shizhuang2020..
  HLBD-C1-5F-FW:
    username: admin
    password: FW@Shizhuang2020..
  HLBD-D3-5F-Core:
    username: admin
    password: Core@Shizhuang2020..
  HLBD-D3-5F-Poe:
    username: admin
    password: Poe@Shizhuang2020..
  HLBD-D3-5F-Access:
    username: admin
    password: Access@Shizhuang2020..
  HLBD-D3-5F-WLC:
    username: admin
    password: WLC@Shizhuang2020..
  SDL-C4-1F-POE:
    username: admin
    password: Poe@Shizhuang2020..
  SDL-C4-2F-Core:
    username: admin
    password: Core@Shizhuang2020..
  SDL-C4-2F-POE:
    username: admin
    passowrd: Poe@Shizhuang2020..
  SDL-C4-2F-SW:
    username: admin
    password: Access@Shizhuang2020..
  SDL-C4-2F-WLC:
    username: admin
    password: WLC@Shizhuang2020..
  SDL-C4-3F-Core:
    username: admin
    password: Core@Shizhuang2020..
  SDL-C4-3F-POE:
    username: admin
    password: Poe@Shizhuang2020..
  SDL-C4-3F-SW:
    username: admin
    password: Access@Shizhuang2020..
  SDL-C4-3F-WLC:
    username: admin
    password: WLC@Shizhuang2020..
  JDCK-D9-FW:
    username: admin
    password: Szd9@2019
  JDCK-D9-Core:
    username: admin
    password: Szd9@2019
  JDCK-D9-WLC:
    username: admin
    password: Szd9@2019
  JDCK-D9-Access:
    username: admin
    password: Szd9@2019
  JDCK-D10-Core:
    username: admin
    password: SZD10@2019
  JDCK-D10-FW:
    username: admin
    password: SZD10@2019
  JDCK-D10-WLC:
    username: admin
    password: SZD10@2019
  JDCK-D10-Access:
    username: admin
    password: SZD10@2019
  JDCK-D8-FW:
    username: admin
    password: 1qaz2wsx3edc$RFV
  JDCK-D8-WLC:
    username: admin
    password: 1qaz2wsx3edc$RFV
  JDCK-D8-Poe:
    username: admin
    password: 1qaz2wsx3edc$RFV
  JDCK-D8-Access:
    username: admin
    password: 1qaz2wsx3edc$RFV
  JDCK-95-Core:
    username: admin
    password: 0okm(IJN
  JDCK-95-Poe:
    username: admin
    password: 0okm(IJN
  JDCK-95-WLC:
    username: admin
    password: 0okm(IJN
  JDCK-95-Access:
    username: admin
    password: 0okm(IJN
models: {}
pid: "/root/.config/oxidized/pid"
crash:
  directory: "/root/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  file:
    directory: "/root/.config/oxidized/configs"
  git:
    single_repo: true
    user: chenjun-oxidized2020
    email: chenjun@theduapp.com
    repo: "/root/.config/oxidized/devices.git"
source:
  default: csv
  csv:
    file: "/root/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2
#      username: 3
#      password: 4
model_map:
  huawei: vrp
  cisco: ios
  h3c: comware

**Comment by ytti** [comment] 2020-03-19 09:21
Duplicate of #2049

**Closed by ytti** 2020-03-19 09:21 UTC
Labels: triage

**Comment by chenjun-oxidized2020** [comment] 2020-03-19 09:28
> Duplicate of #2049

The problem is in output/git.rb on this line
walker.push(repo.head.target)

I've not written this code, but walker.push (now) expects Data not Rugged::Commit, so this code is broken on current version of rugged.

Do I need to comment this line of code to solve this problem?

**Comment by ytti** [comment] 2020-03-19 09:35
Read the issue, there is link a commit where this is fixed.

**Comment by chenjun-oxidized2020** [comment] 2020-03-20 03:37
> Read the issue, there is link a commit where this is fixed.

thank you very much
