### ISSUE TITLE
Unable to back up opengear devices since 4.11.0 'could not settle on hmac_client algorithm'

### ISSUE THREAD

**Issue by rkerr** [ytti/oxidized#2468] opened 2022-02-07 10:24 UTC
Since updating firmware on out opengear devices we are unable to back them up with the error `could not settle on hmac_client algorithm`. Digging through the opengear changelog we find version 4.11.0 lists:

 - Improve OpenSSH default cipher strength

And testing with openssh in verbose mode we find the MACs offered by the opengear are:

`debug2: MACs stoc: umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com`

None of these algorithms are supported by net-ssh 5, but they are supported by net-ssh 6. It seems that this issue is similar to #2043 and to support these newer devices net-ssh 6 will be required.

I note there is a concern in #2043 about maintaining support for older devices, referencing net-ssh/net-ssh#709 but I don't see that this should be a major issue as that change only disables the algorithms by default and adds a `append_all_supported_algorithms: true` option to re-enable them.

**Comment by tach47** [comment] 2022-02-09 01:44
I'm having the same issue, like most opengear users keeping their firmware up to date. #2314 appears to be active-ish.

**Comment by mortzu** [comment] 2022-03-04 13:43
duplicate of #2314

**Closed by mortzu** 2022-03-04 13:43 UTC
