### ISSUE TITLE
MySQL Example Database/Table

### ISSUE THREAD

**Issue by brianblac** [ytti/oxidized#1167] opened 2018-01-27 21:11 UTC
Looking to see if anyone would be willing to share an example sql file for how they have built their database table for storing their source devices?

**Comment by brianblac** [comment] 2018-01-28 01:23
For context here's what I'm doing:

Table SQL:
CREATE TABLE `nodes` (
  `id` int(10) UNSIGNED NOT NULL,
  `name` text NOT NULL,
  `ip` text NOT NULL,
  `model` text NOT NULL,
  `group` text NOT NULL,
  `enabled` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

Source Config:
source:
  default: sql
  sql:
    adapter: mysql2
    database: oxidized
    table: nodes
    user: oxidized
    password: oxipw
    query: "SELECT * FROM nodes WHERE enabled = True"
    map:
      name: name
      ip: ip
      model: model
      group: group

Everything is working great, just wondering what others are doing. I'm still defining the username/passwords in the config file due to me not wanting them in the database for this application.

**Comment by jsynack** [comment] 2018-01-28 18:02
DB tables are often tied to what you may already have for your nodelist. This looks like a good start.

One thing that is personal preference of mine - is to avoid the MySQL reserved words such as 'name', 'group' etc.  I use ``nn`` (for nodename) and ``gn`` (for 'groupname') . But this may just be personal preference to make some of the CLI interactions go smoother on the tables.

**Comment by brianblac** [comment] 2018-01-28 20:41
It's funny you mention that, I ended up having to change 'group' last night to better work my php scripts.

Appreciate the input!

**Comment by laf** [comment] 2018-01-31 20:26
You can also wrap column names and table names in ` ` ` marks.

I'm closing this issue as it's not a bug or request of Oxidized. You can discuss things like this within the gitter support channel.

**Closed by laf** 2018-01-31 20:26 UTC
