### ISSUE TITLE
HP Procurve "Timed out while waiting for more data"

### ISSUE THREAD

**Issue by PPITadmin** [ytti/oxidized#612] opened 2016-11-08 19:41 UTC
I have two HP Procurve switches that give:
 `WARN -- : 192.168.X.X raised Timeout::Error with msg "timed out while waiting for more data"
`
when Oxidized attempts to connect via telnet. The telnet log also gives a strange output:  
```
Connected to 192.168.X.X.
[24;1H

[?25h[24;11H[2J[?7l[3;23r[?6l[1;1H[?25l[1;1HProCurve J9280A Switch 2510G-48

Software revision Y.11.01


Copyright (C) 1991-2008 Hewlett-Packard Co.  All Rights Reserved.


                           RESTRICTED RIGHTS LEGEND


 Use, duplication, or disclosure by the Government is subject to restrictions

 as set forth in subdivision (b) (3) (ii) of the Rights in Technical Data and

 Computer Software clause at 52.227-7013.


HEWLETT-PACKARD COMPANY, 3000 Hanover St., Palo Alto, CA 94303


We'd like to keep you up to date about:

  * Software feature updates

  * New product announcements

  * Special events


Please register your products now at:  www.ProCurve.com



[24;1HPress any key to continue[1;1H[?25h[24;27H[2J[?7l[3;23r[?6l[24;27H[?25h[24;27H[?6l[1;24r[?7l[2J[24;27H[1;24r[24;27H[24;1HPassword: [?25h[24;1H[?25h[24;11HTrying 192.168.
```

Switches are: 
HP J4813A ProCurve Switch 2524, revision F.05.50, ROM F.02.01
ProCurve J9280A Switch 2510G-48, revision Y.11.01, ROM N.10.02

**Comment by wk** [comment] 2018-04-29 08:52
The `procurve.rb` model has seen significant change since this issue was created. Please re-test this with a recent version of Oxidized, and if you can reproduce the defect, re-open this issue with a fresh debug log.

Closing for now.

**Closed by wk** 2018-04-29 08:52 UTC
