### ISSUE TITLE
nodes list in oxidized web interface

### ISSUE THREAD

**Issue by PeepOks** [ytti/oxidized#1370] opened 2018-06-07 14:02 UTC
After installing oxidized 0.22.0, web interface very slowly displays nodes. If I have ~5 nodes then page will show up but when ~500 nodes I will get timeout.
puma version 3.11.3

**Comment by ytti** [comment] 2018-06-07 18:00
This probably should be opened in oxidized-web.

I possibly broke it here: https://github.com/ytti/oxidized-web/commit/f800c0f6d306847239367f27898c2a12bca9a332

I can make some poc code to revert it, if you're interested in testing.

**Comment by PeepOks** [comment] 2018-06-08 05:36
I can test that poc code.

**Comment by ytti** [comment] 2018-06-08 13:35
Try this https://github.com/ytti/oxidized-web/commit/33ac63993199407f024c2fcb9b4f4c457793855d

**Comment by davama** [comment] 2018-06-08 15:07
Hello @ytti thank you for posting a fix

I was following this post cuz i noticed this behavior. (3 systems with combined total of ~10000 nodes)
Prior to @PeepOks posting i was running `v0.21.0` with no issue. After the upgrade this happened.

Just wanted to add that i tried your code above but no change :frowning: 
I reduced my oxidized-db to 5 nodes and the web UI comes up. Increase to 100 and nothing...

Thank you for the support!
dave

**Comment by ytti** [comment] 2018-06-08 18:32
Maybe this? https://github.com/ytti/oxidized-web/commit/ec5344e06a5540732ccb2d5ccf71af8c5020cda0

Is it specifically listing nodes which times out? Everything else works?

**Comment by davama** [comment] 2018-06-08 19:42
@ytti thank you 
Sorry, im a bit confused.

 > Maybe this? ytti/oxidized-web@ec5344e

Are you asking to try the revert of those changes while keeping these https://github.com/ytti/oxidized-web/commit/33ac63993199407f024c2fcb9b4f4c457793855d ? I see that they were committed on April 20.

**Comment by davama** [comment] 2018-06-08 19:43
OH! and to answer question:

> Is it specifically listing nodes which times out? Everything else works?

Just node list, at least in my enviroment. Backups are fine

**Comment by kylemclerren** [comment] 2018-06-08 21:46
I also have this issue, which happened after upgrading. nodes takes ~9 mins to load.

**Comment by ytti** [comment] 2018-06-08 21:52
I welcome to people to review

https://github.com/ytti/oxidized-web/compare/0.9.3...0.10.2
https://github.com/ytti/oxidized/compare/0.21.0...0.22.0

grab some knives, turn off the light and get stabby

**Comment by ytti** [comment] 2018-06-08 21:54
Is it also slow to just fetch the node list JSON? Or only rendered node list?

**Comment by kylemclerren** [comment] 2018-06-08 21:56
im happy to help test that. how do i fetch the node list JSON?

**Comment by ytti** [comment] 2018-06-09 18:05
In the URL add .json.  What is the slow url? Is it /nodes or /nodes/stats?

**Comment by PeepOks** [comment] 2018-06-11 09:00
I tested poc code and it didn't help.
There is no big time difference in requesting nodes list in html or json. Page still loads very slowly. 
For me there is no problem loading "/nodes/stats"  or "/node/show/" page.

When loading "/nodes/group/routers" or "/nodes/model/IOS" I get an error message.
```
file: webapp.rb location: block (2 levels) in <class:WebApp> line: 33 
```

sinatra.error | #<NoMethodError: undefined method `[]' for nil:NilClass>
-- | --
sinatra.route | GET /nodes/:filter/:value.?:format?

**Comment by davama** [comment] 2018-06-11 13:16
Downgraded to 0.21.0 and 0.9.3 and things look "normal", at least this ticket is concerned.

> grab some knives, turn off the light and get stabby

going to look at oxidized-web begin from Nov 1, 2017 https://github.com/ytti/oxidized-web/commit/1034ac9c8a065895eea91149652f827603a44369

```
git rev-list -1 --before="Dec 04 2017" master --format=medium
commit 1034ac9c8a065895eea91149652f827603a44369
Author: Neil Lathwood <neil@lathwood.co.uk>
Date:   Wed Nov 1 22:18:45 2017 +0000

    release: Bump version to 0.9.3 (#146)

git checkout 1034ac9c8a065895eea91149652f827603a44369
HEAD is now at 1034ac9... release: Bump version to 0.9.3 (#146)
```
will report back when it breaks... hehe :smile:

**Comment by ytti** [comment] 2018-06-11 13:48
@PeepOks @davama just to confirm, it is slow to do curl foo/nodes.json?

**Comment by ytti** [comment] 2018-06-11 13:51
I think this broke it: 
https://github.com/ytti/oxidized-web/commit/ec5344e06a5540732ccb2d5ccf71af8c5020cda0#diff-47d361ba06e54d45074a986db1405e11

I think asking for versions is expensive, can someone try to get rid of the ```mtime``` and ```versions``` and see if without fetching those, it's fast?

If so, then I can purpose solution to make recovering mtime faster.

**Comment by davama** [comment] 2018-06-11 14:00
> I think this broke it:
ytti/oxidized-web@ec5344e#diff-47d361ba06e54d45074a986db1405e11

wow! i was just testing this one myself. i think it did too since reverting back to https://github.com/ytti/oxidized-web/commit/7622c7eb099d66d5fdefa8b4d9eae31771b93eb2 works fine. 

> I think asking for versions is expensive, can someone try to get rid of the mtime and versions and see if without fetching those, it's fast?

let me try

**Comment by davama** [comment] 2018-06-11 14:20
@ytti i tested from commit https://github.com/ytti/oxidized-web/commit/ec5344e but with removing https://github.com/ytti/oxidized-web/commit/ec5344e06a5540732ccb2d5ccf71af8c5020cda0#diff-47d361ba06e54d45074a986db1405e11 and listing the nodes on the web browser loads fine. 

also tested latest versions 0.22.0 and 0.10.2 but removing the specific commit and it works!!!  yay!

**Comment by ytti** [comment] 2018-06-11 14:22
Can someone test mtime branch

https://github.com/ytti/oxidized/tree/feature-mtime
https://github.com/ytti/oxidized-web/tree/feature-mtime

a) is it same speed at before regression
b) is mtime shown for nodes (force some config change to get mtime somewhere)

**Comment by davama** [comment] 2018-06-11 20:27
> https://github.com/ytti/oxidized/tree/feature-mtime

```
git clone -b feature-mtime https://github.com/ytti/oxidized-web.git
Cloning into 'oxidized-web'...
remote: Counting objects: 1212, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 1212 (delta 17), reused 32 (delta 11), pack-reused 1169
Receiving objects: 100% (1212/1212), 402.50 KiB | 0 bytes/s, done.
Resolving deltas: 100% (527/527), done.

cd oxidized-web/
git log -1 --pretty=%B
mtime is now exposed in the serialised format

gem build oxidized-web.gemspec 
  Successfully built RubyGem
  Name: oxidized-web
  Version: 0.10.2
  File: oxidized-web-0.10.2.gem

gem install oxidized-web-0.10.2.gem 
Successfully installed oxidized-web-0.10.2
Parsing documentation for oxidized-web-0.10.2
1 gem installed
```

> https://github.com/ytti/oxidized-web/tree/feature-mtime
 
```
git clone -b feature-mtime https://github.com/ytti/oxidized.git
Cloning into 'oxidized'...
remote: Counting objects: 8614, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 8614 (delta 36), reused 66 (delta 33), pack-reused 8530
Receiving objects: 100% (8614/8614), 1.48 MiB | 1.42 MiB/s, done.
Resolving deltas: 100% (5057/5057), done.

cd oxidized
git log -1 --pretty=%B
set default value for mtime

gem build oxidized.gemspec 
  Successfully built RubyGem
  Name: oxidized
  Version: 0.22.0
  File: oxidized-0.22.0.gem

gem install oxidized-0.22.0.gem 
Successfully installed oxidized-0.22.0
Parsing documentation for oxidized-0.22.0
1 gem installed
```
> a) is it same speed at before regression

at least to me, yes

> b) is mtime shown for nodes (force some config change to get mtime somewhere)

if im looking at it right, yes
![image](https://i.imgur.com/rTylADq.png)

**Comment by davama** [comment] 2018-06-11 20:38
Just to asnwer the curl question...

```
curl -X GET  'http://localhost:9002/oxidized/nodes.json' | jq .
{
    "name": "mys-1kua-r14-ap-1",
    "full_name": "MYS_WIFI/mys-1kua-r14-ap-1",
    "ip": "<redacted>",
    "group": "MYS_WIFI",
    "model": "IOS",
    "last": null,
    "vars": {
      "enable": null
    },
    "mtime": "unknown",
    "status": "never",
    "time": "never"
  },
.....
```
it's pretty fast

**Comment by ytti** [comment] 2018-06-11 21:24
Awesome, thank you so much @davama 

I'll release new oxidized-web and oxidized as gems shortly

**Comment by ytti** [comment] 2018-06-11 21:32
0.23.0 and 0.11.0 should be released, lessee how it goes :>

**Comment by ytti** [comment] 2018-06-11 21:56
0.11.1 missed one line :/

**Comment by kylemclerren** [comment] 2018-06-11 23:58
i can verify the update has fixed my issue. thank you so much for your work on this project!

**Comment by PeepOks** [comment] 2018-06-12 07:29
I can also confirm that update 0.23.0 and 0.11.1 fixed issues

**Comment by ytti** [comment] 2018-06-12 08:41
@davama @kylemclerren @PeepOks thanks for verifying and apologies for the inconvenience, closing the case.

**Closed by ytti** 2018-06-12 08:41 UTC
Labels: bug, regression

**Comment by davama** [comment] 2018-06-12 12:04
@ytti thank you for the support
