### ISSUE TITLE
Oxidized-0-21 to starting after initial install

### ISSUE THREAD

**Issue by papatango71** [ytti/oxidized#1178] opened 2018-02-07 18:27 UTC
I am getting the following error on a fresh install of oxidized:

[/home/oxidized/.config/oxidized]$ oxidized
Error loading config: (<unknown>): found character that cannot start any token while scanning for the next token at line 49 column 15
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/config.rb:53:in `rescue in load': Error loading config: (<unknown>): found character that cannot start any token while scanning for the next token at line 49 column 15 (Oxidized::InvalidConfig)
	from /usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/config.rb:50:in `load'
	from /usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/cli.rb:24:in `initialize'
	from /usr/local/share/gems/gems/oxidized-0.21.0/bin/oxidized:9:in `new'
	from /usr/local/share/gems/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'

This is the output of the crash file:

Inappropriate ioctl for device [Errno::ENOTTY]
--------------------------------------------------
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/prompt.rb:44:in `noecho'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/prompt.rb:44:in `ask'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:53:in `block (2 levels) in authenticate'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:50:in `times'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:50:in `block in authenticate'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:20:in `loop'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:20:in `authenticate'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `each'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh.rb:237:in `start'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/input/ssh.rb:49:in `connect'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/node.rb:65:in `run_input'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/node.rb:42:in `block in run'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/node.rb:37:in `each'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/node.rb:37:in `run'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/job.rb:9:in `block in initialize'

Any help to get this issue resolved would be greatly appreciated.

**Comment by laf** [comment] 2018-02-07 20:10
You’ve already opened this issue and I’ve closed it. The same response still applies. 

Looks like a config issue, if you use librenms you can paste it into the validator within that or just use a normal yaml validator online.

This is best discussed in the forum or gitter as it's not a bug in oxidized

**Closed by laf** 2018-02-07 20:10 UTC
