### ISSUE TITLE
Requesting multiple sources

### ISSUE THREAD

**Issue by kungfu1234** [ytti/oxidized#685] opened 2017-02-02 18:09 UTC
Hello,

I would like to request the ability to use multiple sources. IE - cvs, as well as http. Or, more than one csv, or more than one http source.

In my particular circumstance, i have more than one librenms instance, and it would be easiest if i could use two http sources. Or in the event i cannot use http for some reason, to be able to read from a csv.

Thank you!

**Comment by ytti** [comment] 2017-02-02 18:48
We have request for multiple outputs as well, and it's definitely something we can pretty easily support. I'm not going planning on working this for now, but think this is something we should support.

**Comment by laf** [comment] 2017-07-02 20:03
@ytti This is a duplicate of #625.

**Closed** 2017-07-03 09:58 UTC
Labels: enhancement, soliciting_pr
