### ISSUE TITLE
edgeswitch with enable password does not work

### ISSUE THREAD

**Issue by paszczus** [ytti/oxidized#2070] opened 2020-04-18 19:26 UTC
`, [2020-04-18T21:14:12.483978 #26332]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2020-04-18T21:14:12.813519 #26332]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
show running-config
                        ^
% Invalid input detected at '^' marker.

(UBNT EdgeSwitch) >`

**Comment by mikecook** [comment] 2022-03-18 23:29
dupe of https://github.com/ytti/oxidized/issues/1853

**Closed** 2022-03-24 10:30 UTC
Labels: triage
