### ISSUE TITLE
New gem release

### ISSUE THREAD

**Issue by ciroiriarte** [ytti/oxidized#2646] opened 2022-10-22 17:51 UTC
As a feature request :)

Can we get an official gem release update?, the current one is from 2020. If contribution to make it happen is needed, how can we contribute to make it happen?

Ref:
https://rubygems.org/gems/oxidized/versions/0.28.0

**Comment by smurdza** [comment] 2022-10-25 12:39
@Firefishy, Is there a specific release date for the new gem? Can you write if it is planned at all? Ruby 3.0 compatibility is important for OS v el9 deployment. EL9 doesn't support Ruby 2.x :(

**Comment by mortzu** [comment] 2022-10-26 10:05
duplicate of #2517

**Closed by mortzu** 2022-10-26 10:05 UTC
